[font]
normal = { family = "MartianMono Nerd Font Mono" }
# offset = { x = 0, y = 0 }
size = 9
# builtin_box_drawing = false

[window]
startup_mode = "Maximized"

[colors.primary]
background = "#12100f"
